# =============================================================================
# federated_core/ml/data_loader.py
# ----------------------------------
# Multimodal data loading for Federated Learning.
#
# Wraps torchvision.datasets.ImageFolder to load MRI images from the
# archive (2) directory, and pairs each image with a synthetic clinical
# feature vector generated by SyntheticClinicalGenerator.
#
# Provides IID partitioning for FL simulation and a held-out global
# test set for centralized server evaluation.
#
# Author: Kasyap (Final-Year Academic Project)
# =============================================================================

from __future__ import annotations

import os
import sys
from typing import Tuple, List, Optional

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import datasets, transforms

# Add project root to path for imports
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from federated_core.ml.synthetic_features import SyntheticClinicalGenerator


# ─────────────────────────────────────────────────────────────────────────────
# Default dataset paths (relative to project root)
# ─────────────────────────────────────────────────────────────────────────────
_DEFAULT_TRAIN_DIR = os.path.join(
    _PROJECT_ROOT, "archive (2)", "AugmentedAlzheimerDataset"
)
_DEFAULT_TEST_DIR = os.path.join(
    _PROJECT_ROOT, "archive (2)", "OriginalDataset"
)


# ─────────────────────────────────────────────────────────────────────────────
# Image transforms
# ─────────────────────────────────────────────────────────────────────────────
def get_train_transforms() -> transforms.Compose:
    """
    Training transforms with data augmentation.

    Pipeline:
        1. Resize to 224×224 (ResNet-18 input size)
        2. Random horizontal flip (brain symmetry augmentation)
        3. Random rotation ±10° (mild orientation variation)
        4. Convert to tensor [0, 1]
        5. Normalize to mean=0.5, std=0.5 → range [-1, 1]
    """
    return transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.Grayscale(num_output_channels=1),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(degrees=10),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5], std=[0.5]),
    ])


def get_eval_transforms() -> transforms.Compose:
    """
    Evaluation transforms (no augmentation).

    Pipeline:
        1. Resize to 224×224
        2. Convert to tensor [0, 1]
        3. Normalize to mean=0.5, std=0.5
    """
    return transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5], std=[0.5]),
    ])


# ─────────────────────────────────────────────────────────────────────────────
# Multimodal Dataset
# ─────────────────────────────────────────────────────────────────────────────
class AlzheimerMultimodalDataset(Dataset):
    """
    Multimodal dataset pairing MRI images with synthetic clinical features.

    Wraps torchvision.datasets.ImageFolder and generates class-conditional
    synthetic tabular features for each sample.

    Each __getitem__ returns:
        mri_tensor:      (1, 224, 224) — grayscale MRI slice
        clinical_tensor: (9,)          — z-score normalized clinical features
        label:           int           — class index (0–3)
    """

    def __init__(
        self,
        image_dir: str,
        transform: Optional[transforms.Compose] = None,
        synthetic_seed: int = 42,
    ) -> None:
        """
        Args:
            image_dir:      Path to ImageFolder-compatible directory
                            (subdirectories = class names).
            transform:      Torchvision transforms for image preprocessing.
            synthetic_seed: Random seed for synthetic feature generation.
        """
        if transform is None:
            transform = get_eval_transforms()

        self.image_dataset: datasets.ImageFolder = datasets.ImageFolder(
            root=image_dir,
            transform=transform,
        )

        self.clinical_generator = SyntheticClinicalGenerator(seed=synthetic_seed)

        # Log class mapping
        self.class_to_idx = self.image_dataset.class_to_idx
        self.classes = self.image_dataset.classes
        print(f"[DataLoader] Loaded {len(self)} samples from: {image_dir}")
        print(f"[DataLoader] Class mapping: {self.class_to_idx}")

    def __len__(self) -> int:
        return len(self.image_dataset)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, int]:
        """
        Returns:
            mri_tensor:      (1, 224, 224) preprocessed MRI image
            clinical_tensor: (9,) z-score normalized clinical features
            label:           integer class label
        """
        # Image + label from ImageFolder
        mri_tensor, label = self.image_dataset[idx]

        # Generate synthetic clinical features for this class
        clinical_array = self.clinical_generator.generate_normalized(label)
        clinical_tensor = torch.tensor(clinical_array, dtype=torch.float32)

        return mri_tensor, clinical_tensor, label


# ─────────────────────────────────────────────────────────────────────────────
# Data Partitioning for Federated Learning
# ─────────────────────────────────────────────────────────────────────────────
def partition_data(
    dataset: AlzheimerMultimodalDataset,
    num_partitions: int,
    partition_id: int,
    val_split: float = 0.2,
    batch_size: int = 32,
    seed: int = 42,
) -> Tuple[DataLoader, DataLoader]:
    """
    IID partition of the dataset for a specific FL client.

    Splits the full dataset indices into num_partitions equal parts,
    then further splits the assigned partition into train/val subsets.

    Args:
        dataset:         The full AlzheimerMultimodalDataset.
        num_partitions:  Total number of FL clients.
        partition_id:    This client's partition index (0-based).
        val_split:       Fraction reserved for local validation.
        batch_size:      DataLoader batch size.
        seed:            Random seed for reproducible partitioning.

    Returns:
        (train_loader, val_loader) for this partition.
    """
    # Shuffle all indices
    rng = np.random.RandomState(seed)
    all_indices = rng.permutation(len(dataset))

    # Split into num_partitions equal parts
    partition_indices = np.array_split(all_indices, num_partitions)
    my_indices = partition_indices[partition_id]

    # Split into train/val
    split_idx = int(len(my_indices) * (1.0 - val_split))
    train_indices = my_indices[:split_idx]
    val_indices = my_indices[split_idx:]

    train_subset = Subset(dataset, train_indices.tolist())
    val_subset = Subset(dataset, val_indices.tolist())

    train_loader = DataLoader(
        train_subset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,      # Windows compatibility
        drop_last=False,
    )

    val_loader = DataLoader(
        val_subset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        drop_last=False,
    )

    print(
        f"[Partition {partition_id}] Train: {len(train_indices)} samples, "
        f"Val: {len(val_indices)} samples"
    )

    return train_loader, val_loader


def load_global_test_set(
    test_dir: Optional[str] = None,
    batch_size: int = 64,
) -> DataLoader:
    """
    Load the centralized global test set from the OriginalDataset.

    Used for server-side evaluation after each FL aggregation round.

    Args:
        test_dir:   Path to the test dataset directory.
        batch_size: DataLoader batch size.

    Returns:
        DataLoader for the global test set.
    """
    if test_dir is None:
        test_dir = _DEFAULT_TEST_DIR

    test_dataset = AlzheimerMultimodalDataset(
        image_dir=test_dir,
        transform=get_eval_transforms(),
        synthetic_seed=0,  # Fixed seed for consistent test features
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        drop_last=False,
    )

    return test_loader


def compute_class_weights(dataset: AlzheimerMultimodalDataset) -> torch.Tensor:
    """
    Compute inverse-frequency class weights for CrossEntropyLoss.

    Handles class imbalance by assigning higher weights to minority classes:
        w_c = N / (K × n_c)
    where N = total samples, K = num classes, n_c = samples in class c.

    Args:
        dataset: The multimodal dataset.

    Returns:
        torch.Tensor of shape (num_classes,) with class weights.
    """
    targets = [dataset.image_dataset.targets[i] for i in range(len(dataset))]
    class_counts = np.bincount(targets)
    total = len(targets)
    num_classes = len(class_counts)

    weights = total / (num_classes * class_counts.astype(np.float32) + 1e-6)

    print(f"[DataLoader] Class counts: {dict(enumerate(class_counts.tolist()))}")
    print(f"[DataLoader] Class weights: {dict(enumerate(weights.tolist()))}")

    return torch.tensor(weights, dtype=torch.float32)
